# Generated by Django 2.1.7 on 2019-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='end_point',
            field=models.CharField(default='/', max_length=100, verbose_name='访问端点'),
        ),
    ]
