# Generated by Django 2.1.7 on 2019-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后访问时间'),
        ),
    ]
