# Generated by Django 2.1.7 on 2019-04-02 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190331_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后访问时间'),
        ),
    ]
