# Generated by Django 2.2 on 2019-04-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userip_created_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitNumber',
        ),
    ]
