# Generated by Django 2.1.7 on 2019-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='total',
            name='category_nums',
            field=models.IntegerField(default=0, verbose_name='分类数'),
        ),
        migrations.AlterField(
            model_name='total',
            name='comment_nums',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
