# Generated by Django 2.1.7 on 2019-04-12 04:59

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='category',
            name='navigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Navigation', verbose_name='分类导航'),
        ),
    ]
