# Generated by Django 2.1.7 on 2019-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190412_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='/static/images/python.jpg', upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片'),
        ),
    ]
