# Generated by Django 2.1.7 on 2019-04-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190411_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='navigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Navigation', verbose_name='分类导航'),
        ),
    ]
