# Generated by Django 2.1.7 on 2019-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190324_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, verbose_name='用户头像'),
        ),
    ]
