# Generated by Django 2.1.7 on 2019-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190324_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='用户头像'),
        ),
    ]
