# Generated by Django 2.1.7 on 2019-04-12 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190412_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='navigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Navigation', verbose_name='分类导航'),
        ),
    ]
