# Generated by Django 2.1.7 on 2019-03-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190324_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='linkurl',
            new_name='link_url',
        ),
    ]
