# Generated by Django 2.1.7 on 2019-04-02 23:12

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190329_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=300, verbose_name='信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客事件信息',
                'verbose_name_plural': '博客事件信息',
                'ordering': ['created_time'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, default='', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=40, verbose_name='链接名称'),
        ),
    ]
