# Generated by Django 2.0.1 on 2019-04-02 23:38

from django.db import migrations
from mdeditor import fields as md_models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0012_auto_20190402_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=md_models.MDTextField(blank=True, verbose_name='内容'),
        ),
    ]
