# Generated by Django 2.0.1 on 2019-04-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='U_content',
        ),
    ]
