# Generated by Django 2.0.1 on 2019-04-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190402_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='U_content',
            new_name='body',
        ),
    ]
