# Generated by Django 2.0.1 on 2019-04-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_article_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='body',
        ),
    ]
