# Generated by Django 2.0.1 on 2019-04-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190403_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='format_content',
            field=models.TextField(blank=True, verbose_name='格式化内容'),
        ),
    ]
