# Generated by Django 2.2 on 2019-04-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190403_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_nums', models.IntegerField(default=0, verbose_name='文章数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='分类数')),
                ('tag_nums', models.IntegerField(default=0, verbose_name='标签数')),
                ('category_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('visit_nums', models.IntegerField(default=0, verbose_name='访问总数')),
            ],
            options={
                'verbose_name': '博客统计信息',
                'verbose_name_plural': '博客统计信息',
            },
        ),
    ]
