# Generated by Django 2.0.1 on 2019-03-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=40, verbose_name='站点名称')),
                ('keywords', models.CharField(max_length=200, verbose_name='站点关键字')),
                ('desc', models.TextField(verbose_name='站点描述')),
                ('copyright', models.CharField(max_length=200, verbose_name='站点版权')),
                ('code', models.CharField(max_length=200, verbose_name='备案号')),
            ],
        ),
    ]
