# Generated by Django 2.1.7 on 2019-03-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='评论者')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('avatar', models.ImageField(blank=True, max_length=255, upload_to='avatar/', verbose_name='用户头像')),
                ('url', models.URLField(blank=True, verbose_name='网站地址')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': '站点信息', 'verbose_name_plural': '站点信息'},
        ),
    ]
