# Generated by Django 2.1.7 on 2019-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='browser',
            field=models.CharField(default='', max_length=100, verbose_name='浏览器'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ip_addr',
            field=models.CharField(default='', max_length=100, verbose_name='IP地址'),
        ),
    ]
