# Generated by Django 2.1.7 on 2019-04-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190401_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='browser',
            field=models.CharField(max_length=100, verbose_name='浏览器'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip_addr',
            field=models.CharField(max_length=100, verbose_name='位置'),
        ),
    ]
